service: serverless-websockets
frameworkVersion: '=2.33.0'

plugins:
  - serverless-functions-base-path
  - serverless-iam-roles-per-function
  - serverless-dynamodb-local
  - serverless-webpack
  - serverless-offline

custom:
  resourcePrefix: ${self:service}-${self:provider.stage}
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

  functionsBasePath: src/functions

  serverless-offline:
    websocketPort: 3001
    lambdaPort: 3002
    host: localhost
    noPrependStageInUrl: true

  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      migrate: true
      seed: true
      convertEmptyValues: true
      # Uncomment only if you already have a DynamoDB running locally
      # noStart: true

    seed:
      test:
        sources:
          - table: ${self:custom.resourcePrefix}-connections
            sources: [./seed/connections.json]

package:
  individually: true

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 256
  stage: dev
  region: ap-southeast-2
  websocketsApiName: serverless-websockets-api # Use a custom name for the websockets API
  websocketsApiRouteSelectionExpression: $request.body.action # custom route selection expression
  lambdaHashingVersion: 20201221

  iamRoleStatements:
    - Effect: Allow
      Action:
        - 'execute-api:ManageConnections'
      Resource:
        - 'arn:aws:execute-api:*:*:**/@connections/*'
    - Effect: Allow
      Action:
        - dynamodb:PutItem
      Resource: !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${self:custom.resourcePrefix}-connections

  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    CONNECTIONS_TABLE: ${self:custom.resourcePrefix}-connections
    APIG_ENDPOINT:
      Fn::Join:
        - ''
        - - Ref: WebsocketsApi
          - .execute-api.
          - Ref: AWS::Region
          - .amazonaws.com/
          - ${self:provider.stage}

functions:
  - ${file(./resources/functions.yml)}

resources:
  - ${file(./resources/dynamodb.yml)}
